import { prisma } from "../src/config/database";
import bcrypt from "bcryptjs";

const IMG = (id: string) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=800&q=80`;
const IMG2 = (id: string) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=800&q=75`;

// Curated Unsplash photo IDs for each car type
const PHOTOS = {
  tesla3:      "1560958089-b8a1929cea89",
  teslaS:      "1619767886558-efdc259b6e09",
  teslaX:      "1617650728657-cc5e8df43d67",
  bmwElec:     "1555215695-3004980ad54e",
  audiEtron:   "1614200179396-2bdb77ebf81b",
  ioniq:       "1662450346146-24e5d59013e8",
  rivian:      "1632766068228-cb54e3d36cd4",
  porsche911:  "1614162692292-7ac56d7f7f1e",
  porscheConv: "1580273916550-e323be2ae537",
  ferrari:     "1592198084033-aade902d1aae",
  ferrariP:    "1583121274602-3e2820c69888",
  lambo:       "1544636331-e26879cd4d9b",
  mclaren:     "1620882813876-02e078a6358c",
  astonMartin: "1603584173870-7f23fdae1b7a",
  civic:       "1552519507-da3b142c6e3d",
  corvette:    "1547744152-14d985cb937f",
  jagF:        "1598457002018-c2b3e404b901",
  bmwM4:       "1541899481282-d53bffe3c35d",
  rollsRoyce:  "1631295868223-63265b40d9e4",
  bentley:     "1503376780353-7e6692767b70",
  mercedesS:   "1618843479313-40f8afb4b4d8",
  mercedesGLS: "1594966779313-e7a9bb3142da",
  audiA8:      "1549317661-bd32c8ce0db2",
  lexus:       "1623910382367-eafa04e7b8a7",
  maserati:    "1610444321743-162e0a29f8f4",
  rangeRover:  "1606148633261-7bc46700c01b",
  defender:    "1605350383186-b48cde070c53",
  jeep:        "1533473359331-0135ef1b58bf",
  bmwX5:       "1556189250-72ba954cfc2b",
  cayenne:     "1617814076367-b759c7d7e738",
  camry:       "1621007947382-bb3c3994e3fb",
  accord:      "1568844293986-ca9c5b63f4fd",
  mercedesC:   "1606664515524-ed2f786a0bd6",
  alfaRomeo:   "1622394595232-a52cfde10972",
  f150:        "1558618666-fcd25c85cd64",
  hilux:       "1569336415962-a4bd9f69cd83",
  hummer:      "1629897042531-ad6e59ad768a",
  vBuzz:       "1659550731093-61bba1033230",
  vClass:      "1564557287817-3785e38ec1f5",
  luxury:      "1494976388531-d1058494cdd8",
};

async function main() {
  console.log("🌱 Seeding database...");

  const categoryNames = ["Sedan", "SUV", "Electric", "Sports", "Luxury", "Convertible", "Truck", "Van"];
  const categories = await Promise.all(
    categoryNames.map((name) =>
      prisma.category.upsert({ where: { name }, update: {}, create: { name } })
    )
  );
  console.log(`✅ ${categories.length} categories ready`);

  const passwordHash = await bcrypt.hash("password123", 12);

  const lendersData = [
    { name: "Sarah Connor",         email: "sarah@example.com",              role: "lender" as any, isVerified: true, passwordHash },
    { name: "Michael Knight",       email: "michael@example.com",            role: "lender" as any, isVerified: true, passwordHash },
    { name: "Bruce Wayne",          email: "bruce@waynecorp.com",            role: "lender" as any, isVerified: true, passwordHash },
    { name: "Tony Stark",           email: "tony@starkindustries.com",        role: "lender" as any, isVerified: true, passwordHash },
    { name: "Olivia Martinez",      email: "olivia@luxurycars.ng",           role: "lender" as any, isVerified: true, passwordHash },
    { name: "Chukwuemeka Obi",      email: "emeka@elitecars.ng",             role: "lender" as any, isVerified: true, passwordHash },
    { name: "Funmilayo Adeyemi",    email: "funmi@premiumdrives.ng",         role: "lender" as any, isVerified: true, passwordHash },
    { name: "Babatunde Okafor",     email: "tunde@luxuryfleet.ng",           role: "lender" as any, isVerified: true, passwordHash },
    { name: "Amara Nwosu",          email: "amara@nwosucars.ng",             role: "lender" as any, isVerified: true, passwordHash },
    { name: "Kehinde Adeleke",      email: "kehinde@adelekemotors.ng",       role: "lender" as any, isVerified: true, passwordHash },
  ];

  const lenders = await Promise.all(
    lendersData.map(({ email, ...rest }) =>
      prisma.user.upsert({
        where: { email },
        // Always refresh name, role, isVerified, and passwordHash so existing
        // Google-OAuth-only accounts get a usable password on re-seed.
        update: { ...rest },
        create: { email, ...rest },
      })
    )
  );
  console.log(`✅ ${lenders.length} lenders ready`);

  const cat = (name: string) => categories.find((c) => c.name === name)!;

  // ─────────────────────────────────────────────────────────────────────────
  // 100 CARS
  // ─────────────────────────────────────────────────────────────────────────
  const carsData = [

    // ── ELECTRIC (12) ──────────────────────────────────────────────────────
    {
      title: "Tesla Model 3 Performance",
      brand: "Tesla", model: "Model 3", year: 2023,
      description: "Dual-motor AWD, 0-60 in 3.1s, autopilot, 360-mile range. The benchmark electric sedan.",
      pricePerDay: 120, locationCity: "Lagos", category: "Electric",
      fuelType: "Electric", transmission: "Automatic", seats: 5,
      topSpeed: 162, acceleration: "3.1s", enginePower: "450hp",
      mainImage: PHOTOS.tesla3, extraImage: IMG2(PHOTOS.teslaS),
    },
    {
      title: "Tesla Model S Plaid",
      brand: "Tesla", model: "Model S", year: 2024,
      description: "Tri-motor 1,020hp, 0-60 in 1.99s. The fastest production sedan ever built.",
      pricePerDay: 280, locationCity: "Abuja", category: "Electric",
      fuelType: "Electric", transmission: "Automatic", seats: 5,
      topSpeed: 200, acceleration: "1.99s", enginePower: "1020hp",
      mainImage: PHOTOS.teslaS, extraImage: IMG2(PHOTOS.tesla3),
    },
    {
      title: "Tesla Model X Plaid",
      brand: "Tesla", model: "Model X", year: 2024,
      description: "Falcon-wing doors, 1,020hp, seating for 7. The SUV that defies physics.",
      pricePerDay: 320, locationCity: "Lagos", category: "Electric",
      fuelType: "Electric", transmission: "Automatic", seats: 7,
      topSpeed: 163, acceleration: "2.5s", enginePower: "1020hp",
      mainImage: PHOTOS.teslaX, extraImage: IMG2(PHOTOS.tesla3),
    },
    {
      title: "Tesla Model Y Long Range",
      brand: "Tesla", model: "Model Y", year: 2024,
      description: "All-wheel drive, 330-mile range, spacious cabin. The world's best-selling EV.",
      pricePerDay: 110, locationCity: "Ikeja", category: "Electric",
      fuelType: "Electric", transmission: "Automatic", seats: 5,
      topSpeed: 135, acceleration: "4.8s", enginePower: "384hp",
      mainImage: PHOTOS.tesla3, extraImage: IMG2(PHOTOS.teslaX),
    },
    {
      title: "BMW i4 M50",
      brand: "BMW", model: "i4 M50", year: 2023,
      description: "544hp electric gran coupé. M-tuned chassis, 0-60 in 3.7s, 300-mile range.",
      pricePerDay: 200, locationCity: "Lagos", category: "Electric",
      fuelType: "Electric", transmission: "Automatic", seats: 5,
      topSpeed: 140, acceleration: "3.7s", enginePower: "544hp",
      mainImage: PHOTOS.bmwElec, extraImage: IMG2(PHOTOS.audiEtron),
    },
    {
      title: "BMW iX M60",
      brand: "BMW", model: "iX M60", year: 2024,
      description: "619hp electric luxury SUV. Ultra-luxurious cabin, 288-mile range, head-turning presence.",
      pricePerDay: 240, locationCity: "Abuja", category: "Electric",
      fuelType: "Electric", transmission: "Automatic", seats: 5,
      topSpeed: 155, acceleration: "3.8s", enginePower: "619hp",
      mainImage: PHOTOS.bmwElec, extraImage: IMG2(PHOTOS.rangeRover),
    },
    {
      title: "Audi RS e-tron GT",
      brand: "Audi", model: "RS e-tron GT", year: 2024,
      description: "646hp quattro electric GT. 0-60 in 3.1s, OLED tail-lights, air suspension — future is now.",
      pricePerDay: 350, locationCity: "Victoria Island", category: "Electric",
      fuelType: "Electric", transmission: "Automatic", seats: 4,
      topSpeed: 155, acceleration: "3.1s", enginePower: "646hp",
      mainImage: PHOTOS.audiEtron, extraImage: IMG2(PHOTOS.bmwElec),
    },
    {
      title: "Hyundai Ioniq 6 N Line",
      brand: "Hyundai", model: "Ioniq 6", year: 2024,
      description: "Aerodynamic streamliner, 320-mile range, ultra-fast 800V charging. K-style excellence.",
      pricePerDay: 140, locationCity: "Lekki", category: "Electric",
      fuelType: "Electric", transmission: "Automatic", seats: 5,
      topSpeed: 115, acceleration: "5.1s", enginePower: "320hp",
      mainImage: PHOTOS.ioniq, extraImage: IMG2(PHOTOS.tesla3),
    },
    {
      title: "Hyundai Ioniq 5 N",
      brand: "Hyundai", model: "Ioniq 5 N", year: 2024,
      description: "641hp track-ready electric crossover. Simulated gear shifts, drift mode, pure insanity.",
      pricePerDay: 190, locationCity: "Lagos", category: "Electric",
      fuelType: "Electric", transmission: "Automatic", seats: 5,
      topSpeed: 161, acceleration: "3.4s", enginePower: "641hp",
      mainImage: PHOTOS.ioniq, extraImage: IMG2(PHOTOS.bmwElec),
    },
    {
      title: "Rivian R1T Adventure Edition",
      brand: "Rivian", model: "R1T", year: 2023,
      description: "Quad-motor 835hp electric pickup. Goes anywhere, carries everything, charges fast.",
      pricePerDay: 250, locationCity: "Abuja", category: "Electric",
      fuelType: "Electric", transmission: "Automatic", seats: 5,
      topSpeed: 110, acceleration: "3.0s", enginePower: "835hp",
      mainImage: PHOTOS.rivian, extraImage: IMG2(PHOTOS.f150),
    },
    {
      title: "Porsche Taycan Turbo S",
      brand: "Porsche", model: "Taycan", year: 2024,
      description: "760hp electric sports sedan. 0-60 in 2.6s, air suspension, the purist's EV choice.",
      pricePerDay: 420, locationCity: "Lagos", category: "Electric",
      fuelType: "Electric", transmission: "Automatic", seats: 4,
      topSpeed: 161, acceleration: "2.6s", enginePower: "760hp",
      mainImage: PHOTOS.porsche911, extraImage: IMG2(PHOTOS.audiEtron),
    },
    {
      title: "Mercedes-Benz EQS 580",
      brand: "Mercedes", model: "EQS 580", year: 2023,
      description: "516hp luxury electric limo. 350-mile range, MBUX Hyperscreen, whisper-quiet at any speed.",
      pricePerDay: 380, locationCity: "Victoria Island", category: "Electric",
      fuelType: "Electric", transmission: "Automatic", seats: 5,
      topSpeed: 130, acceleration: "4.3s", enginePower: "516hp",
      mainImage: PHOTOS.mercedesS, extraImage: IMG2(PHOTOS.audiA8),
    },

    // ── SPORTS (15) ────────────────────────────────────────────────────────
    {
      title: "Porsche 911 Carrera S",
      brand: "Porsche", model: "911 Carrera S", year: 2023,
      description: "450hp flat-six, 0-60 in 3.5s. The icon that defined sports car perfection for 60 years.",
      pricePerDay: 450, locationCity: "Lagos", category: "Sports",
      fuelType: "Petrol", transmission: "Automatic", seats: 4,
      topSpeed: 191, acceleration: "3.5s", enginePower: "450hp",
      mainImage: PHOTOS.porsche911, extraImage: IMG2(PHOTOS.porscheConv),
    },
    {
      title: "Porsche 911 GT3 RS",
      brand: "Porsche", model: "911 GT3 RS", year: 2024,
      description: "518hp naturally-aspirated flat-six. Downforce exceeds body weight. Pure track weapon.",
      pricePerDay: 650, locationCity: "Victoria Island", category: "Sports",
      fuelType: "Petrol", transmission: "Manual", seats: 2,
      topSpeed: 185, acceleration: "3.2s", enginePower: "518hp",
      mainImage: PHOTOS.porscheConv, extraImage: IMG2(PHOTOS.porsche911),
    },
    {
      title: "Ferrari Roma",
      brand: "Ferrari", model: "Roma", year: 2022,
      description: "620hp twin-turbo V8 grand tourer. La dolce vita distilled into one breathtaking machine.",
      pricePerDay: 850, locationCity: "Lekki", category: "Sports",
      fuelType: "Petrol", transmission: "Automatic", seats: 4,
      topSpeed: 199, acceleration: "3.4s", enginePower: "620hp",
      mainImage: PHOTOS.ferrari, extraImage: IMG2(PHOTOS.ferrariP),
    },
    {
      title: "Ferrari F8 Tributo",
      brand: "Ferrari", model: "F8 Tributo", year: 2023,
      description: "710hp mid-rear V8. Ferrari's tribute to the most beloved V8 engine in its history.",
      pricePerDay: 1100, locationCity: "Lagos", category: "Sports",
      fuelType: "Petrol", transmission: "Automatic", seats: 2,
      topSpeed: 211, acceleration: "2.9s", enginePower: "710hp",
      mainImage: PHOTOS.ferrariP, extraImage: IMG2(PHOTOS.ferrari),
    },
    {
      title: "Lamborghini Huracán EVO",
      brand: "Lamborghini", model: "Huracán EVO", year: 2023,
      description: "631hp naturally-aspirated V10. The sound alone is worth every naira.",
      pricePerDay: 1200, locationCity: "Lagos", category: "Sports",
      fuelType: "Petrol", transmission: "Automatic", seats: 2,
      topSpeed: 202, acceleration: "2.9s", enginePower: "631hp",
      mainImage: PHOTOS.lambo, extraImage: IMG2(PHOTOS.ferrari),
    },
    {
      title: "McLaren 720S",
      brand: "McLaren", model: "720S", year: 2022,
      description: "710hp twin-turbo V8, dihedral doors, 0-60 in 2.7s. McLaren's most capable sports car.",
      pricePerDay: 1300, locationCity: "Victoria Island", category: "Sports",
      fuelType: "Petrol", transmission: "Automatic", seats: 2,
      topSpeed: 212, acceleration: "2.7s", enginePower: "710hp",
      mainImage: PHOTOS.mclaren, extraImage: IMG2(PHOTOS.lambo),
    },
    {
      title: "McLaren GT",
      brand: "McLaren", model: "GT", year: 2023,
      description: "620hp V8 grand tourer. Luggage in the boot AND front. Daily supercar perfected.",
      pricePerDay: 900, locationCity: "Lagos", category: "Sports",
      fuelType: "Petrol", transmission: "Automatic", seats: 2,
      topSpeed: 203, acceleration: "3.2s", enginePower: "620hp",
      mainImage: PHOTOS.mclaren, extraImage: IMG2(PHOTOS.astonMartin),
    },
    {
      title: "Aston Martin Vantage",
      brand: "Aston Martin", model: "Vantage", year: 2023,
      description: "503hp AMG-sourced V8. British predator with a bark as vicious as its bite.",
      pricePerDay: 800, locationCity: "Lekki", category: "Sports",
      fuelType: "Petrol", transmission: "Automatic", seats: 2,
      topSpeed: 195, acceleration: "3.6s", enginePower: "503hp",
      mainImage: PHOTOS.astonMartin, extraImage: IMG2(PHOTOS.mclaren),
    },
    {
      title: "Aston Martin DBX707",
      brand: "Aston Martin", model: "DBX707", year: 2023,
      description: "707hp — the world's most powerful SUV. Aston's crown jewel in an SUV body.",
      pricePerDay: 750, locationCity: "Abuja", category: "Sports",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 193, acceleration: "3.3s", enginePower: "707hp",
      mainImage: PHOTOS.astonMartin, extraImage: IMG2(PHOTOS.rangeRover),
    },
    {
      title: "Honda Civic Type R",
      brand: "Honda", model: "Civic Type R", year: 2023,
      description: "315hp FWD track car. Nürburgring record holder. The most exciting hatchback on earth.",
      pricePerDay: 130, locationCity: "Ikeja", category: "Sports",
      fuelType: "Petrol", transmission: "Manual", seats: 5,
      topSpeed: 169, acceleration: "5.0s", enginePower: "315hp",
      mainImage: PHOTOS.civic, extraImage: IMG2(PHOTOS.accord),
    },
    {
      title: "Chevrolet Corvette C8 Stingray",
      brand: "Chevrolet", model: "Corvette C8", year: 2023,
      description: "495hp mid-engine American supercar. Ferrari performance at a fraction of the cost.",
      pricePerDay: 380, locationCity: "Abuja", category: "Sports",
      fuelType: "Petrol", transmission: "Automatic", seats: 2,
      topSpeed: 194, acceleration: "2.9s", enginePower: "495hp",
      mainImage: PHOTOS.corvette, extraImage: IMG2(PHOTOS.porsche911),
    },
    {
      title: "Nissan GT-R Premium",
      brand: "Nissan", model: "GT-R", year: 2022,
      description: "565hp twin-turbo V6 AWD. 'Godzilla' — Japan's legendary supercar slayer.",
      pricePerDay: 420, locationCity: "Lagos", category: "Sports",
      fuelType: "Petrol", transmission: "Automatic", seats: 4,
      topSpeed: 196, acceleration: "2.7s", enginePower: "565hp",
      mainImage: PHOTOS.civic, extraImage: IMG2(PHOTOS.corvette),
    },
    {
      title: "Jaguar F-Type R",
      brand: "Jaguar", model: "F-Type R", year: 2022,
      description: "575hp supercharged V8. The most visceral sounding car in its class. British thunder.",
      pricePerDay: 320, locationCity: "Lagos", category: "Sports",
      fuelType: "Petrol", transmission: "Automatic", seats: 2,
      topSpeed: 186, acceleration: "3.5s", enginePower: "575hp",
      mainImage: PHOTOS.jagF, extraImage: IMG2(PHOTOS.astonMartin),
    },
    {
      title: "BMW M2 Competition",
      brand: "BMW", model: "M2", year: 2023,
      description: "460hp S58 engine from the M3/M4. The purest, most driver-focused BMW ever built.",
      pricePerDay: 280, locationCity: "Lekki", category: "Sports",
      fuelType: "Petrol", transmission: "Manual", seats: 4,
      topSpeed: 177, acceleration: "4.1s", enginePower: "460hp",
      mainImage: PHOTOS.bmwM4, extraImage: IMG2(PHOTOS.porsche911),
    },
    {
      title: "BMW M4 Competition",
      brand: "BMW", model: "M4 Competition", year: 2023,
      description: "503hp inline-six, xDrive AWD. Track day champion that doubles as a daily driver.",
      pricePerDay: 360, locationCity: "Lagos", category: "Sports",
      fuelType: "Petrol", transmission: "Automatic", seats: 4,
      topSpeed: 180, acceleration: "3.5s", enginePower: "503hp",
      mainImage: PHOTOS.bmwM4, extraImage: IMG2(PHOTOS.bmwElec),
    },

    // ── LUXURY (15) ────────────────────────────────────────────────────────
    {
      title: "Rolls-Royce Ghost",
      brand: "Rolls-Royce", model: "Ghost", year: 2023,
      description: "563hp V12, starlight headliner, whisper cabin. The art of absolute luxury travel.",
      pricePerDay: 1500, locationCity: "Lagos", category: "Luxury",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 155, acceleration: "4.8s", enginePower: "563hp",
      mainImage: PHOTOS.rollsRoyce, extraImage: IMG2(PHOTOS.bentley),
    },
    {
      title: "Rolls-Royce Cullinan Black Badge",
      brand: "Rolls-Royce", model: "Cullinan", year: 2024,
      description: "600hp V12 luxury SUV. The most expensive SUV on Earth. Moves mountains in silence.",
      pricePerDay: 1800, locationCity: "Victoria Island", category: "Luxury",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 155, acceleration: "5.0s", enginePower: "600hp",
      mainImage: PHOTOS.rollsRoyce, extraImage: IMG2(PHOTOS.mercedesGLS),
    },
    {
      title: "Bentley Continental GT V8 S",
      brand: "Bentley", model: "Continental GT", year: 2023,
      description: "542hp handcrafted GT. Mulliner interior, diamond-quilted leather, W12 at your beck.",
      pricePerDay: 950, locationCity: "Victoria Island", category: "Luxury",
      fuelType: "Petrol", transmission: "Automatic", seats: 4,
      topSpeed: 198, acceleration: "4.0s", enginePower: "542hp",
      mainImage: PHOTOS.bentley, extraImage: IMG2(PHOTOS.rollsRoyce),
    },
    {
      title: "Bentley Bentayga EWB",
      brand: "Bentley", model: "Bentayga EWB", year: 2023,
      description: "542hp extended-wheelbase SUV. Chair-table rear seats, limousine legroom in an SUV.",
      pricePerDay: 1100, locationCity: "Abuja", category: "Luxury",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 180, acceleration: "4.5s", enginePower: "542hp",
      mainImage: PHOTOS.bentley, extraImage: IMG2(PHOTOS.mercedesGLS),
    },
    {
      title: "Bentley Flying Spur Hybrid",
      brand: "Bentley", model: "Flying Spur", year: 2023,
      description: "544hp V6 hybrid 4-door GT. Business class in a car that still embarrasses sports cars.",
      pricePerDay: 880, locationCity: "Lagos", category: "Luxury",
      fuelType: "Hybrid", transmission: "Automatic", seats: 5,
      topSpeed: 177, acceleration: "4.0s", enginePower: "544hp",
      mainImage: PHOTOS.bentley, extraImage: IMG2(PHOTOS.audiA8),
    },
    {
      title: "Mercedes-Maybach S680",
      brand: "Mercedes", model: "S680 Maybach", year: 2024,
      description: "621hp V12 ultra-luxury sedan. Executive rear cabin, champagne cooler, first-class skies on asphalt.",
      pricePerDay: 1200, locationCity: "Lagos", category: "Luxury",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 155, acceleration: "5.0s", enginePower: "621hp",
      mainImage: PHOTOS.mercedesS, extraImage: IMG2(PHOTOS.bentley),
    },
    {
      title: "Mercedes-Maybach GLS 600",
      brand: "Mercedes", model: "GLS 600 Maybach", year: 2024,
      description: "550hp V8 luxury SUV. Magic Body Control, panoramic roof, rear seat entertainment.",
      pricePerDay: 1100, locationCity: "Abuja", category: "Luxury",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 155, acceleration: "4.9s", enginePower: "550hp",
      mainImage: PHOTOS.mercedesGLS, extraImage: IMG2(PHOTOS.rollsRoyce),
    },
    {
      title: "Audi A8 L",
      brand: "Audi", model: "A8 L", year: 2023,
      description: "335hp V6 flagship sedan. Predictive active suspension, rear-seat massage, quattro AWD.",
      pricePerDay: 320, locationCity: "Abuja", category: "Luxury",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 155, acceleration: "5.7s", enginePower: "335hp",
      mainImage: PHOTOS.audiA8, extraImage: IMG2(PHOTOS.mercedesS),
    },
    {
      title: "Lexus LS 500h",
      brand: "Lexus", model: "LS 500h", year: 2023,
      description: "354hp hybrid V6. Japanese omotenashi hospitality on wheels — serene, refined, unmatched.",
      pricePerDay: 280, locationCity: "Lagos", category: "Luxury",
      fuelType: "Hybrid", transmission: "Automatic", seats: 5,
      topSpeed: 149, acceleration: "5.3s", enginePower: "354hp",
      mainImage: PHOTOS.lexus, extraImage: IMG2(PHOTOS.audiA8),
    },
    {
      title: "Lexus LC 500 Inspiration",
      brand: "Lexus", model: "LC 500", year: 2023,
      description: "471hp naturally-aspirated V8 coupe. Stunning design, orchestra exhaust note, handcrafted interior.",
      pricePerDay: 400, locationCity: "Abuja", category: "Luxury",
      fuelType: "Petrol", transmission: "Automatic", seats: 4,
      topSpeed: 168, acceleration: "4.4s", enginePower: "471hp",
      mainImage: PHOTOS.lexus, extraImage: IMG2(PHOTOS.bentley),
    },
    {
      title: "Maserati Quattroporte Trofeo",
      brand: "Maserati", model: "Quattroporte", year: 2023,
      description: "523hp Ferrari-derived V8. Italian opera meets executive transport — bellissimo.",
      pricePerDay: 600, locationCity: "Abuja", category: "Luxury",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 193, acceleration: "4.5s", enginePower: "523hp",
      mainImage: PHOTOS.maserati, extraImage: IMG2(PHOTOS.ferrari),
    },
    {
      title: "Maserati Levante Trofeo",
      brand: "Maserati", model: "Levante Trofeo", year: 2022,
      description: "580hp Ferrari V8 SUV. The first SUV with the soul of an Italian stallion.",
      pricePerDay: 520, locationCity: "Lagos", category: "Luxury",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 187, acceleration: "3.9s", enginePower: "580hp",
      mainImage: PHOTOS.maserati, extraImage: IMG2(PHOTOS.cayenne),
    },
    {
      title: "BMW 7 Series M760e xDrive",
      brand: "BMW", model: "7 Series M760e", year: 2024,
      description: "571hp PHEV flagship. Sky Lounge panoramic roof, executive lounge rear seats, theatre screen.",
      pricePerDay: 460, locationCity: "Lagos", category: "Luxury",
      fuelType: "Hybrid", transmission: "Automatic", seats: 5,
      topSpeed: 155, acceleration: "3.8s", enginePower: "571hp",
      mainImage: PHOTOS.bmwElec, extraImage: IMG2(PHOTOS.mercedesS),
    },
    {
      title: "Genesis G90 Limousine",
      brand: "Genesis", model: "G90", year: 2024,
      description: "375hp twin-turbo V6. Korean luxury at its absolute pinnacle — threatens Benz and BMW.",
      pricePerDay: 350, locationCity: "Ibadan", category: "Luxury",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 155, acceleration: "5.1s", enginePower: "375hp",
      mainImage: PHOTOS.audiA8, extraImage: IMG2(PHOTOS.mercedesS),
    },
    {
      title: "Lincoln Navigator Black Label",
      brand: "Lincoln", model: "Navigator", year: 2023,
      description: "440hp twin-turbo V6 luxury SUV. Reclining rear seats, 30-speaker Revel audio, American prestige.",
      pricePerDay: 480, locationCity: "Port Harcourt", category: "Luxury",
      fuelType: "Petrol", transmission: "Automatic", seats: 7,
      topSpeed: 130, acceleration: "5.9s", enginePower: "440hp",
      mainImage: PHOTOS.mercedesGLS, extraImage: IMG2(PHOTOS.lexus),
    },

    // ── SUV (18) ───────────────────────────────────────────────────────────
    {
      title: "Range Rover Sport P530",
      brand: "Land Rover", model: "Range Rover Sport", year: 2023,
      description: "530hp V8 with air suspension. Off-road supremacy meets Mayfair elegance in one package.",
      pricePerDay: 280, locationCity: "Abuja", category: "SUV",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 155, acceleration: "4.3s", enginePower: "530hp",
      mainImage: PHOTOS.rangeRover, extraImage: IMG2(PHOTOS.defender),
    },
    {
      title: "Range Rover Autobiography P530",
      brand: "Land Rover", model: "Range Rover", year: 2024,
      description: "530hp flagship SUV. Four-zone climate, meridian surround sound, the car of heads of state.",
      pricePerDay: 650, locationCity: "Lagos", category: "SUV",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 155, acceleration: "4.6s", enginePower: "530hp",
      mainImage: PHOTOS.rangeRover, extraImage: IMG2(PHOTOS.rollsRoyce),
    },
    {
      title: "Land Rover Defender 130",
      brand: "Land Rover", model: "Defender 130", year: 2024,
      description: "396hp V8, 8-seat configuration, class IV tow rating. Adventure for the whole crew.",
      pricePerDay: 310, locationCity: "Lekki", category: "SUV",
      fuelType: "Petrol", transmission: "Automatic", seats: 8,
      topSpeed: 149, acceleration: "5.4s", enginePower: "396hp",
      mainImage: PHOTOS.defender, extraImage: IMG2(PHOTOS.rangeRover),
    },
    {
      title: "Land Rover Defender 110 V8",
      brand: "Land Rover", model: "Defender 110", year: 2023,
      description: "518hp V8 Defender. The original icon now with supercharged power — unstoppable off-road.",
      pricePerDay: 260, locationCity: "Ikeja", category: "SUV",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 149, acceleration: "5.0s", enginePower: "518hp",
      mainImage: PHOTOS.defender, extraImage: IMG2(PHOTOS.jeep),
    },
    {
      title: "Jeep Wrangler Rubicon 392",
      brand: "Jeep", model: "Wrangler Rubicon", year: 2023,
      description: "470hp V8 Wrangler. Removable doors, roof-off, locking diffs — built for the wild.",
      pricePerDay: 150, locationCity: "Lekki", category: "SUV",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 112, acceleration: "4.5s", enginePower: "470hp",
      mainImage: PHOTOS.jeep, extraImage: IMG2(PHOTOS.defender),
    },
    {
      title: "Jeep Grand Cherokee Trackhawk",
      brand: "Jeep", model: "Grand Cherokee Trackhawk", year: 2021,
      description: "707hp supercharged V8 SUV. 0-60 in 3.5s. The Hellcat engine in family SUV clothing.",
      pricePerDay: 340, locationCity: "Abuja", category: "SUV",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 180, acceleration: "3.5s", enginePower: "707hp",
      mainImage: PHOTOS.jeep, extraImage: IMG2(PHOTOS.bmwX5),
    },
    {
      title: "BMW X5 M Competition",
      brand: "BMW", model: "X5 M Competition", year: 2023,
      description: "627hp twin-turbo V8. Track-day performance wrapped in school-run practicality.",
      pricePerDay: 340, locationCity: "Lagos", category: "SUV",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 177, acceleration: "3.8s", enginePower: "627hp",
      mainImage: PHOTOS.bmwX5, extraImage: IMG2(PHOTOS.cayenne),
    },
    {
      title: "BMW X7 M60i",
      brand: "BMW", model: "X7 M60i", year: 2024,
      description: "530hp V8 luxury 7-seater. The largest and most powerful BMW SUV — executive family transport.",
      pricePerDay: 380, locationCity: "Abuja", category: "SUV",
      fuelType: "Petrol", transmission: "Automatic", seats: 7,
      topSpeed: 155, acceleration: "4.7s", enginePower: "530hp",
      mainImage: PHOTOS.bmwX5, extraImage: IMG2(PHOTOS.mercedesGLS),
    },
    {
      title: "Porsche Cayenne GTS",
      brand: "Porsche", model: "Cayenne GTS", year: 2023,
      description: "460hp twin-turbo V8 with sport-tuned chassis. Handles like a 911 but carries five.",
      pricePerDay: 310, locationCity: "Ikeja", category: "SUV",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 168, acceleration: "4.5s", enginePower: "460hp",
      mainImage: PHOTOS.cayenne, extraImage: IMG2(PHOTOS.bmwX5),
    },
    {
      title: "Porsche Cayenne Turbo GT",
      brand: "Porsche", model: "Cayenne Turbo GT", year: 2023,
      description: "631hp coupe SUV. 0-60 in 3.1s. Set the Nürburgring SUV lap record.",
      pricePerDay: 480, locationCity: "Lagos", category: "SUV",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 186, acceleration: "3.1s", enginePower: "631hp",
      mainImage: PHOTOS.cayenne, extraImage: IMG2(PHOTOS.lambo),
    },
    {
      title: "Mercedes-AMG G63",
      brand: "Mercedes", model: "G63 AMG", year: 2023,
      description: "577hp twin-turbo V8 G-Wagon. The box on wheels that everyone wants. Pure street royalty.",
      pricePerDay: 720, locationCity: "Lagos", category: "SUV",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 137, acceleration: "4.5s", enginePower: "577hp",
      mainImage: PHOTOS.mercedesS, extraImage: IMG2(PHOTOS.rangeRover),
    },
    {
      title: "Mercedes-AMG GLE 63 S",
      brand: "Mercedes", model: "GLE 63 S", year: 2023,
      description: "612hp hybrid V8 SUV. 0-60 in 3.7s. Brabus-ready, drama included, practicality guaranteed.",
      pricePerDay: 520, locationCity: "Abuja", category: "SUV",
      fuelType: "Hybrid", transmission: "Automatic", seats: 5,
      topSpeed: 155, acceleration: "3.7s", enginePower: "612hp",
      mainImage: PHOTOS.mercedesGLS, extraImage: IMG2(PHOTOS.bmwX5),
    },
    {
      title: "Audi RS Q8",
      brand: "Audi", model: "RS Q8", year: 2023,
      description: "591hp twin-turbo V8. Lamborghini Urus DNA, quattro AWD. The RS treatment for an SUV.",
      pricePerDay: 450, locationCity: "Victoria Island", category: "SUV",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 155, acceleration: "3.8s", enginePower: "591hp",
      mainImage: PHOTOS.audiA8, extraImage: IMG2(PHOTOS.cayenne),
    },
    {
      title: "Lamborghini Urus S",
      brand: "Lamborghini", model: "Urus S", year: 2024,
      description: "666hp V8 super SUV. Scissor-door DNA in an SUV. 0-60 in 3.5s — fastest SUV on earth.",
      pricePerDay: 1050, locationCity: "Lagos", category: "SUV",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 190, acceleration: "3.5s", enginePower: "666hp",
      mainImage: PHOTOS.lambo, extraImage: IMG2(PHOTOS.cayenne),
    },
    {
      title: "Toyota Land Cruiser 300 GR Sport",
      brand: "Toyota", model: "Land Cruiser 300", year: 2023,
      description: "415hp twin-turbo V6. 70 years of legend evolved. Built for Africa's toughest terrain.",
      pricePerDay: 290, locationCity: "Abuja", category: "SUV",
      fuelType: "Petrol", transmission: "Automatic", seats: 7,
      topSpeed: 130, acceleration: "6.7s", enginePower: "415hp",
      mainImage: PHOTOS.rangeRover, extraImage: IMG2(PHOTOS.hilux),
    },
    {
      title: "Ford Bronco Wildtrak",
      brand: "Ford", model: "Bronco Wildtrak", year: 2022,
      description: "330hp EcoBoost V6, 35\" Sasquatch tires, removable doors. Off-road legend reborn.",
      pricePerDay: 175, locationCity: "Lekki", category: "SUV",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 100, acceleration: "6.5s", enginePower: "330hp",
      mainImage: PHOTOS.jeep, extraImage: IMG2(PHOTOS.defender),
    },
    {
      title: "Nissan Patrol Platinum",
      brand: "Nissan", model: "Patrol Platinum", year: 2023,
      description: "400hp V8 luxury SUV. The original Nigerian roads conqueror — in full platinum spec.",
      pricePerDay: 200, locationCity: "Port Harcourt", category: "SUV",
      fuelType: "Petrol", transmission: "Automatic", seats: 7,
      topSpeed: 130, acceleration: "7.0s", enginePower: "400hp",
      mainImage: PHOTOS.rangeRover, extraImage: IMG2(PHOTOS.bmwX5),
    },
    {
      title: "Cadillac Escalade ESV Premium",
      brand: "Cadillac", model: "Escalade ESV", year: 2024,
      description: "420hp V8 extended luxury SUV. LED screen dashboard, 5G Wi-Fi, presidential presence.",
      pricePerDay: 500, locationCity: "Lagos", category: "SUV",
      fuelType: "Petrol", transmission: "Automatic", seats: 7,
      topSpeed: 130, acceleration: "5.9s", enginePower: "420hp",
      mainImage: PHOTOS.mercedesGLS, extraImage: IMG2(PHOTOS.rollsRoyce),
    },

    // ── SEDAN (15) ─────────────────────────────────────────────────────────
    {
      title: "Toyota Camry Hybrid XSE",
      brand: "Toyota", model: "Camry Hybrid", year: 2024,
      description: "225hp hybrid drivetrain. Business-ready, fuel-sipping, and more stylish than ever.",
      pricePerDay: 80, locationCity: "Lagos", category: "Sedan",
      fuelType: "Hybrid", transmission: "Automatic", seats: 5,
      topSpeed: 112, acceleration: "7.4s", enginePower: "225hp",
      mainImage: PHOTOS.camry, extraImage: IMG2(PHOTOS.accord),
    },
    {
      title: "Honda Accord Sport 2.0T",
      brand: "Honda", model: "Accord Sport", year: 2024,
      description: "192hp turbocharged four-cylinder. Spacious, tech-packed, and punches far above its price.",
      pricePerDay: 75, locationCity: "Ibadan", category: "Sedan",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 137, acceleration: "7.3s", enginePower: "192hp",
      mainImage: PHOTOS.accord, extraImage: IMG2(PHOTOS.camry),
    },
    {
      title: "Mercedes-Benz C300 AMG Line",
      brand: "Mercedes", model: "C300", year: 2023,
      description: "255hp inline-four with 48V mild-hybrid. MBUX infotainment, Burmester audio, pure elegance.",
      pricePerDay: 180, locationCity: "Abuja", category: "Sedan",
      fuelType: "Hybrid", transmission: "Automatic", seats: 5,
      topSpeed: 155, acceleration: "5.8s", enginePower: "255hp",
      mainImage: PHOTOS.mercedesC, extraImage: IMG2(PHOTOS.mercedesS),
    },
    {
      title: "Mercedes-Benz E450 AMG Line",
      brand: "Mercedes", model: "E450", year: 2023,
      description: "375hp inline-six MHEV. Business class between city and airport — effortlessly.",
      pricePerDay: 240, locationCity: "Lagos", category: "Sedan",
      fuelType: "Hybrid", transmission: "Automatic", seats: 5,
      topSpeed: 155, acceleration: "4.9s", enginePower: "375hp",
      mainImage: PHOTOS.mercedesC, extraImage: IMG2(PHOTOS.audiA8),
    },
    {
      title: "BMW M3 Competition xDrive",
      brand: "BMW", model: "M3 Competition", year: 2023,
      description: "503hp S58 engine, 0-60 in 3.4s. The definitive performance sedan — nothing comes close.",
      pricePerDay: 380, locationCity: "Lagos", category: "Sedan",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 180, acceleration: "3.4s", enginePower: "503hp",
      mainImage: PHOTOS.bmwElec, extraImage: IMG2(PHOTOS.bmwM4),
    },
    {
      title: "BMW M5 CS",
      brand: "BMW", model: "M5 CS", year: 2022,
      description: "627hp V8 super sedan. The lightest and most powerful M5 ever — and only 1,000 made.",
      pricePerDay: 480, locationCity: "Lekki", category: "Sedan",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 190, acceleration: "3.0s", enginePower: "627hp",
      mainImage: PHOTOS.bmwM4, extraImage: IMG2(PHOTOS.mercedesC),
    },
    {
      title: "Alfa Romeo Giulia Quadrifoglio",
      brand: "Alfa Romeo", model: "Giulia Quadrifoglio", year: 2023,
      description: "503hp Ferrari-derived V6. Nürburgring record holder. The most passionate sedan on the road.",
      pricePerDay: 280, locationCity: "Lekki", category: "Sedan",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 191, acceleration: "3.9s", enginePower: "503hp",
      mainImage: PHOTOS.alfaRomeo, extraImage: IMG2(PHOTOS.jagF),
    },
    {
      title: "Audi RS7 Sportback",
      brand: "Audi", model: "RS7 Sportback", year: 2023,
      description: "591hp V8 fastback. Five doors, super-coupe looks, quattro AWD. Audi's masterpiece.",
      pricePerDay: 420, locationCity: "Victoria Island", category: "Sedan",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 155, acceleration: "3.6s", enginePower: "591hp",
      mainImage: PHOTOS.audiA8, extraImage: IMG2(PHOTOS.bmwM4),
    },
    {
      title: "Audi S4 Quattro",
      brand: "Audi", model: "S4 Quattro", year: 2023,
      description: "349hp V6 sports sedan. The sleeper — looks stock, drives like a missile.",
      pricePerDay: 220, locationCity: "Ikeja", category: "Sedan",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 155, acceleration: "4.4s", enginePower: "349hp",
      mainImage: PHOTOS.audiA8, extraImage: IMG2(PHOTOS.alfaRomeo),
    },
    {
      title: "Toyota Avalon Hybrid TRD",
      brand: "Toyota", model: "Avalon Hybrid", year: 2023,
      description: "301hp hybrid. Full-size flagship comfort with Toyota reliability. Perfect for long road trips.",
      pricePerDay: 90, locationCity: "Ibadan", category: "Sedan",
      fuelType: "Hybrid", transmission: "Automatic", seats: 5,
      topSpeed: 112, acceleration: "6.8s", enginePower: "301hp",
      mainImage: PHOTOS.camry, extraImage: IMG2(PHOTOS.lexus),
    },
    {
      title: "Lexus ES 350 F Sport",
      brand: "Lexus", model: "ES 350 F Sport", year: 2024,
      description: "302hp V6 with adaptive suspension. Lexus precision and luxury — the quiet achiever.",
      pricePerDay: 160, locationCity: "Lagos", category: "Sedan",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 130, acceleration: "6.7s", enginePower: "302hp",
      mainImage: PHOTOS.lexus, extraImage: IMG2(PHOTOS.audiA8),
    },
    {
      title: "Cadillac CT5-V Blackwing",
      brand: "Cadillac", model: "CT5-V Blackwing", year: 2023,
      description: "668hp supercharged V8. America's answer to the M5 and E63. Nürburgring-tested.",
      pricePerDay: 360, locationCity: "Abuja", category: "Sedan",
      fuelType: "Petrol", transmission: "Manual", seats: 5,
      topSpeed: 200, acceleration: "3.7s", enginePower: "668hp",
      mainImage: PHOTOS.corvette, extraImage: IMG2(PHOTOS.bmwM4),
    },
    {
      title: "Genesis G80 Sport",
      brand: "Genesis", model: "G80 Sport", year: 2023,
      description: "375hp twin-turbo V6. Genesis emerges as the true luxury rival from Korea. Stunning value.",
      pricePerDay: 240, locationCity: "Port Harcourt", category: "Sedan",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 155, acceleration: "5.0s", enginePower: "375hp",
      mainImage: PHOTOS.mercedesC, extraImage: IMG2(PHOTOS.lexus),
    },
    {
      title: "Jaguar XF P300 R-Dynamic",
      brand: "Jaguar", model: "XF P300", year: 2023,
      description: "296hp turbo inline-four. Jaguar beauty in a package that's practical for every occasion.",
      pricePerDay: 200, locationCity: "Lagos", category: "Sedan",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 155, acceleration: "5.9s", enginePower: "296hp",
      mainImage: PHOTOS.jagF, extraImage: IMG2(PHOTOS.alfaRomeo),
    },
    {
      title: "BMW 3 Series M340i",
      brand: "BMW", model: "3 Series M340i", year: 2024,
      description: "382hp inline-six. The sweet spot: performance, luxury, and daily practicality perfected.",
      pricePerDay: 170, locationCity: "Enugu", category: "Sedan",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 155, acceleration: "4.4s", enginePower: "382hp",
      mainImage: PHOTOS.bmwElec, extraImage: IMG2(PHOTOS.mercedesC),
    },

    // ── CONVERTIBLE (8) ────────────────────────────────────────────────────
    {
      title: "Porsche 911 Carrera Cabriolet",
      brand: "Porsche", model: "911 Cabriolet", year: 2023,
      description: "379hp flat-six drop-top. Roof down in 12 seconds — wind in your hair, smile on your face.",
      pricePerDay: 500, locationCity: "Lagos", category: "Convertible",
      fuelType: "Petrol", transmission: "Automatic", seats: 4,
      topSpeed: 183, acceleration: "3.9s", enginePower: "379hp",
      mainImage: PHOTOS.porscheConv, extraImage: IMG2(PHOTOS.porsche911),
    },
    {
      title: "Porsche Boxster GTS 4.0",
      brand: "Porsche", model: "Boxster GTS", year: 2023,
      description: "394hp naturally-aspirated flat-six roadster. The purist's open-air sports car.",
      pricePerDay: 380, locationCity: "Lekki", category: "Convertible",
      fuelType: "Petrol", transmission: "Manual", seats: 2,
      topSpeed: 182, acceleration: "4.0s", enginePower: "394hp",
      mainImage: PHOTOS.porscheConv, extraImage: IMG2(PHOTOS.jagF),
    },
    {
      title: "Ferrari Portofino M",
      brand: "Ferrari", model: "Portofino M", year: 2023,
      description: "612hp retractable hardtop GT. Open-air motoring with Ferrari DNA — la dolce vita.",
      pricePerDay: 950, locationCity: "Victoria Island", category: "Convertible",
      fuelType: "Petrol", transmission: "Automatic", seats: 4,
      topSpeed: 199, acceleration: "3.45s", enginePower: "612hp",
      mainImage: PHOTOS.ferrariP, extraImage: IMG2(PHOTOS.ferrari),
    },
    {
      title: "BMW M4 Competition Cabriolet",
      brand: "BMW", model: "M4 Cabriolet", year: 2022,
      description: "503hp open-top M4. The ultimate M experience — roof down, track performance intact.",
      pricePerDay: 420, locationCity: "Lekki", category: "Convertible",
      fuelType: "Petrol", transmission: "Automatic", seats: 4,
      topSpeed: 180, acceleration: "3.7s", enginePower: "503hp",
      mainImage: PHOTOS.bmwM4, extraImage: IMG2(PHOTOS.porscheConv),
    },
    {
      title: "Lamborghini Huracán EVO Spyder",
      brand: "Lamborghini", model: "Huracán Spyder", year: 2022,
      description: "631hp V10 open-top. The V10 exhaust note plus wind rush equals pure automotive nirvana.",
      pricePerDay: 1350, locationCity: "Lagos", category: "Convertible",
      fuelType: "Petrol", transmission: "Automatic", seats: 2,
      topSpeed: 202, acceleration: "3.1s", enginePower: "631hp",
      mainImage: PHOTOS.lambo, extraImage: IMG2(PHOTOS.ferrariP),
    },
    {
      title: "McLaren 720S Spider",
      brand: "McLaren", model: "720S Spider", year: 2022,
      description: "710hp open carbon-fibre hypercar. The glass roof slides away in 11 seconds. Insanity uncorked.",
      pricePerDay: 1400, locationCity: "Victoria Island", category: "Convertible",
      fuelType: "Petrol", transmission: "Automatic", seats: 2,
      topSpeed: 212, acceleration: "2.8s", enginePower: "710hp",
      mainImage: PHOTOS.mclaren, extraImage: IMG2(PHOTOS.lambo),
    },
    {
      title: "Aston Martin DB11 Volante",
      brand: "Aston Martin", model: "DB11 Volante", year: 2023,
      description: "503hp V8 soft-top grand tourer. Aston's convertible masterpiece — elegant at any speed.",
      pricePerDay: 900, locationCity: "Lagos", category: "Convertible",
      fuelType: "Petrol", transmission: "Automatic", seats: 4,
      topSpeed: 187, acceleration: "4.1s", enginePower: "503hp",
      mainImage: PHOTOS.astonMartin, extraImage: IMG2(PHOTOS.bentley),
    },
    {
      title: "Mercedes-AMG SL 63",
      brand: "Mercedes", model: "AMG SL 63", year: 2023,
      description: "585hp V8 2+2 roadster. 65 years of SL heritage reinvented with AMG muscle.",
      pricePerDay: 680, locationCity: "Abuja", category: "Convertible",
      fuelType: "Petrol", transmission: "Automatic", seats: 4,
      topSpeed: 183, acceleration: "3.6s", enginePower: "585hp",
      mainImage: PHOTOS.mercedesC, extraImage: IMG2(PHOTOS.porscheConv),
    },

    // ── TRUCK (10) ─────────────────────────────────────────────────────────
    {
      title: "Ford F-150 Raptor R",
      brand: "Ford", model: "F-150 Raptor R", year: 2023,
      description: "700hp supercharged V8 off-road truck. Fox Live-Valve suspension. Conquers any terrain.",
      pricePerDay: 210, locationCity: "Abuja", category: "Truck",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 110, acceleration: "4.4s", enginePower: "700hp",
      mainImage: PHOTOS.f150, extraImage: IMG2(PHOTOS.hilux),
    },
    {
      title: "Ram 1500 TRX",
      brand: "Ram", model: "1500 TRX", year: 2023,
      description: "702hp Hellcat V8 pickup. 0-60 in 4.5s. The fastest, most capable truck ever built.",
      pricePerDay: 280, locationCity: "Lagos", category: "Truck",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 118, acceleration: "4.5s", enginePower: "702hp",
      mainImage: PHOTOS.f150, extraImage: IMG2(PHOTOS.hummer),
    },
    {
      title: "GMC Sierra AT4X",
      brand: "GMC", model: "Sierra AT4X", year: 2023,
      description: "420hp V8 professional grade off-roader. Multimatic DSSV shocks, locking diffs, full Pro Grade.",
      pricePerDay: 195, locationCity: "Abuja", category: "Truck",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 105, acceleration: "6.5s", enginePower: "420hp",
      mainImage: PHOTOS.f150, extraImage: IMG2(PHOTOS.rivian),
    },
    {
      title: "Toyota Hilux GR Sport",
      brand: "Toyota", model: "Hilux GR Sport", year: 2023,
      description: "228hp diesel, GR-tuned suspension, widened body kit. Africa's most trusted pickup — elevated.",
      pricePerDay: 95, locationCity: "Kano", category: "Truck",
      fuelType: "Diesel", transmission: "Automatic", seats: 5,
      topSpeed: 105, acceleration: "10.0s", enginePower: "228hp",
      mainImage: PHOTOS.hilux, extraImage: IMG2(PHOTOS.f150),
    },
    {
      title: "Toyota Tundra TRD Pro",
      brand: "Toyota", model: "Tundra TRD Pro", year: 2023,
      description: "389hp twin-turbo V6 hybrid. TRD-tuned FOX shocks, SkyTough bed. Built for adventure.",
      pricePerDay: 175, locationCity: "Abuja", category: "Truck",
      fuelType: "Hybrid", transmission: "Automatic", seats: 5,
      topSpeed: 110, acceleration: "6.0s", enginePower: "389hp",
      mainImage: PHOTOS.hilux, extraImage: IMG2(PHOTOS.f150),
    },
    {
      title: "GMC Hummer EV Edition 1",
      brand: "GMC", model: "Hummer EV", year: 2024,
      description: "1,000hp triple-motor electric supertruck. Crab mode, Lunar Rocker suspension, zero emissions.",
      pricePerDay: 400, locationCity: "Abuja", category: "Truck",
      fuelType: "Electric", transmission: "Automatic", seats: 5,
      topSpeed: 106, acceleration: "3.0s", enginePower: "1000hp",
      mainImage: PHOTOS.hummer, extraImage: IMG2(PHOTOS.rivian),
    },
    {
      title: "Ford Ranger Raptor",
      brand: "Ford", model: "Ranger Raptor", year: 2023,
      description: "288hp twin-turbo V6 mid-size off-road truck. FOX shocks, desert rally ready from the factory.",
      pricePerDay: 155, locationCity: "Lagos", category: "Truck",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 112, acceleration: "7.9s", enginePower: "288hp",
      mainImage: PHOTOS.hilux, extraImage: IMG2(PHOTOS.f150),
    },
    {
      title: "Chevrolet Silverado ZR2",
      brand: "Chevrolet", model: "Silverado ZR2", year: 2023,
      description: "420hp V8 off-road pickup. Multimatic DSSV dampers, front/rear locking diffs, BFG tires.",
      pricePerDay: 190, locationCity: "Port Harcourt", category: "Truck",
      fuelType: "Petrol", transmission: "Automatic", seats: 5,
      topSpeed: 105, acceleration: "6.3s", enginePower: "420hp",
      mainImage: PHOTOS.f150, extraImage: IMG2(PHOTOS.hilux),
    },
    {
      title: "Nissan Navara Pro-4X",
      brand: "Nissan", model: "Navara Pro-4X", year: 2023,
      description: "187hp diesel 4x4. Bilstein shocks, intelligent 4WD, bed liner. The trusted workhorse.",
      pricePerDay: 120, locationCity: "Kano", category: "Truck",
      fuelType: "Diesel", transmission: "Automatic", seats: 5,
      topSpeed: 105, acceleration: "11.0s", enginePower: "187hp",
      mainImage: PHOTOS.hilux, extraImage: IMG2(PHOTOS.f150),
    },
    {
      title: "Mitsubishi L200 Triton Athlete",
      brand: "Mitsubishi", model: "L200 Triton", year: 2023,
      description: "181hp diesel double cab. Super Select 4WD, 3-ton tow capacity, refined cabin for rough roads.",
      pricePerDay: 100, locationCity: "Ibadan", category: "Truck",
      fuelType: "Diesel", transmission: "Automatic", seats: 5,
      topSpeed: 112, acceleration: "12.0s", enginePower: "181hp",
      mainImage: PHOTOS.hilux, extraImage: IMG2(PHOTOS.f150),
    },

    // ── VAN (7) ────────────────────────────────────────────────────────────
    {
      title: "Mercedes-Benz V-Class Marco Polo",
      brand: "Mercedes", model: "V-Class Marco Polo", year: 2023,
      description: "239hp diesel luxury camper van. Fold-out bed, kitchenette, panoramic roof. Adventure luxury.",
      pricePerDay: 220, locationCity: "Lagos", category: "Van",
      fuelType: "Diesel", transmission: "Automatic", seats: 7,
      topSpeed: 130, acceleration: "9.3s", enginePower: "239hp",
      mainImage: PHOTOS.vClass, extraImage: IMG2(PHOTOS.vBuzz),
    },
    {
      title: "Volkswagen ID. Buzz",
      brand: "Volkswagen", model: "ID. Buzz", year: 2024,
      description: "201hp all-electric retro van. Zero emissions, fast charging, iconic design reborn.",
      pricePerDay: 180, locationCity: "Lagos", category: "Van",
      fuelType: "Electric", transmission: "Automatic", seats: 7,
      topSpeed: 90, acceleration: "10.0s", enginePower: "201hp",
      mainImage: PHOTOS.vBuzz, extraImage: IMG2(PHOTOS.vClass),
    },
    {
      title: "Toyota HiAce Commuter GL",
      brand: "Toyota", model: "HiAce Commuter", year: 2023,
      description: "190hp diesel 14-passenger van. The gold standard for executive group transport in Nigeria.",
      pricePerDay: 130, locationCity: "Abuja", category: "Van",
      fuelType: "Diesel", transmission: "Automatic", seats: 14,
      topSpeed: 112, acceleration: "14.0s", enginePower: "190hp",
      mainImage: PHOTOS.vClass, extraImage: IMG2(PHOTOS.vBuzz),
    },
    {
      title: "Mercedes-Benz Sprinter VIP",
      brand: "Mercedes", model: "Sprinter VIP", year: 2023,
      description: "163hp diesel with VIP interior conversion. Leather captains chairs, TV screens, privacy glass.",
      pricePerDay: 260, locationCity: "Lagos", category: "Van",
      fuelType: "Diesel", transmission: "Automatic", seats: 9,
      topSpeed: 100, acceleration: "14.0s", enginePower: "163hp",
      mainImage: PHOTOS.vClass, extraImage: IMG2(PHOTOS.rollsRoyce),
    },
    {
      title: "Ford Transit Custom Trail",
      brand: "Ford", model: "Transit Custom", year: 2023,
      description: "150hp diesel with adventure kit. Ford Sync 4, all-terrain tires, ideal for overland trips.",
      pricePerDay: 145, locationCity: "Port Harcourt", category: "Van",
      fuelType: "Diesel", transmission: "Automatic", seats: 9,
      topSpeed: 100, acceleration: "15.0s", enginePower: "150hp",
      mainImage: PHOTOS.vBuzz, extraImage: IMG2(PHOTOS.vClass),
    },
    {
      title: "Hyundai Staria Premium",
      brand: "Hyundai", model: "Staria Premium", year: 2023,
      description: "177hp diesel MPV from the future. Panoramic windows, VIP Lounge package, space-ship interior.",
      pricePerDay: 160, locationCity: "Abuja", category: "Van",
      fuelType: "Diesel", transmission: "Automatic", seats: 9,
      topSpeed: 112, acceleration: "12.0s", enginePower: "177hp",
      mainImage: PHOTOS.vBuzz, extraImage: IMG2(PHOTOS.vClass),
    },
    {
      title: "Kia Carnival Limousine",
      brand: "Kia", model: "Carnival", year: 2024,
      description: "291hp V6 luxury minivan. Rear captain chairs with leg rest, massage, power curtains.",
      pricePerDay: 150, locationCity: "Lagos", category: "Van",
      fuelType: "Petrol", transmission: "Automatic", seats: 8,
      topSpeed: 118, acceleration: "8.4s", enginePower: "291hp",
      mainImage: PHOTOS.vBuzz, extraImage: IMG2(PHOTOS.lexus),
    },
  ];

  // ─────────────────────────────────────────────────────────────────────────
  // INSERT CARS
  // ─────────────────────────────────────────────────────────────────────────
  let created = 0;
  let skipped = 0;

  for (let i = 0; i < carsData.length; i++) {
    const d = carsData[i];
    const category = cat(d.category);
    const lender = lenders[i % lenders.length];

    const exists = await prisma.car.findFirst({ where: { title: d.title } });
    if (exists) { skipped++; continue; }

    await prisma.car.create({
      data: {
        title:         d.title,
        brand:         d.brand,
        model:         d.model,
        year:          d.year,
        description:   d.description,
        pricePerDay:   d.pricePerDay,
        locationCity:  d.locationCity,
        fuelType:      d.fuelType,
        transmission:  d.transmission,
        seats:         d.seats,
        topSpeed:      d.topSpeed,
        acceleration:  d.acceleration,
        enginePower:   d.enginePower,
        categoryId:    category.id,
        lenderId:      lender.id,
        images: {
          create: [
            { imageUrl: IMG(d.mainImage),  isMain: true,  publicId: `seed_main_${i}`, order: 0 },
            { imageUrl: IMG2(d.extraImage ?? d.mainImage), isMain: false, publicId: `seed_extra_${i}`, order: 1 },
          ],
        },
      },
    });

    created++;
    if (created % 10 === 0) console.log(`  → ${created} cars created...`);
  }

  console.log(`\n🎉 Done! Created ${created} new cars, skipped ${skipped} existing.`);
  console.log(`📊 Total: ${carsData.length} cars across 8 categories with 10 lenders.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
