import js from "@eslint/js";
import tseslint from "typescript-eslint";
import prettier from "eslint-plugin-prettier/recommended";
import globals from "globals";

export default tseslint.config(
  {
    ignores: ["dist", "node_modules", "prisma", "src/generated", "src/generated/**"],
  },
  js.configs.recommended,
  ...tseslint.configs.recommended,
  prettier,
  {
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        ...globals.node,
        ...globals.es2021,
      },
    },
    rules: {
      "@typescript-eslint/no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "@typescript-eslint/no-explicit-any": "off",
      "@typescript-eslint/no-require-imports": "off",
      "@typescript-eslint/no-unsafe-function-type": "off",
      "@typescript-eslint/ban-ts-comment": "off",
      "@typescript-eslint/no-empty-object-type": "off",
      "no-console": "off",
      "no-undef": "off",
      "no-constant-binary-expression": "off",
      "no-empty": "off",
      "no-empty-pattern": "off",
      "no-inner-declarations": "off",
      "no-async-promise-executor": "off",
      "no-useless-catch": "off",
      "no-unsafe-optional-chaining": "off",
      "no-prototype-builtins": "off",
      "no-case-declarations": "off",
      "no-control-regex": "off",
      "no-useless-escape": "off",
      "no-sparse-arrays": "off",
      "no-constant-condition": "off",
      "no-self-assign": "off",
      "no-redeclare": "off",
      "@typescript-eslint/no-unused-expressions": "off",
      "@typescript-eslint/no-this-alias": "off",
      "@typescript-eslint/no-require-imports": "off",
      "no-unused-expressions": "off",
      "no-unsafe-negation": "off",
      "no-empty-character-class": "off",
      "no-regex-spaces": "off",
      "no-obj-calls": "off",
      "no-ex-assign": "off",
      "no-shadow-restricted-names": "off",
      "no-extra-boolean-cast": "off",
      "no-unsafe-finally": "off",
      "no-caller": "off",
      "no-cond-assign": "off",
      "no-func-assign": "off",
      "no-sparse-arrays": "off",
      "no-unreachable": "off",
      "no-dupe-keys": "off",
      "no-duplicate-case": "off",
      "no-useless-escape": "off",
      "no-empty": "off",
      "no-empty-pattern": "off",
      "no-debugger": "warn",
      "no-control-regex": "off",
      "no-octal": "off",
      "no-unsafe-negation": "off",
      "no-unused-labels": "off",
      "no-empty-character-class": "off",
      "no-regex-spaces": "off",
      "no-obj-calls": "off",
      "no-ex-assign": "off",
      "no-shadow-restricted-names": "off",
    },
  },
);
